# 航空订单系统 - AWS部署版本
# 使用AWS RDS数据库，简化配置

version: '3.8'

services:
  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: airline-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.docker.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - airline-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 航空订单系统后端
  backend:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    container_name: airline-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Spring Boot配置
      SPRING_PROFILES_ACTIVE: prod
      
      # AWS RDS数据库配置
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/airline_order_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-airline_app}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
      # 连接池配置
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 2
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 20000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1200000
      
      # JPA配置
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      
      # JWT配置
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 86400000
      
      # 应用配置
      SERVER_PORT: 8080
      
      # 日志配置
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_POSTION: DEBUG
      
      # JVM优化配置
      JAVA_OPTS: -Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom
      
    volumes:
      - app_logs:/app/logs
    networks:
      - airline-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# 数据卷定义
volumes:
  app_logs:
    driver: local

# 网络定义
networks:
  airline-network:
    driver: bridge
