# Docker Compose 文件版本
version: '3.8'

# 定义服务 (即我们的容器)
services:
  # 1. 数据库服务 (PostgreSQL)
  db:
    image: postgres:17
    container_name: airline-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: airlineTest1234  # !!! 请务必修改为一个安全的密码 !!!
      POSTGRES_DB: airline_order_db         # 自动创建名为 airline_order_db 的数据库
    ports:
      - "5432:5432"  # 将主机的5432端口映射到容器的5432, 用于远程连接
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 将数据持久化到名为 postgres-data 的数据卷中
    networks:
      - airline-network
# 定义数据卷
volumes:
  postgres-data: {} # Docker会为我们管理这个数据卷

# 定义网络
networks:
  airline-network: {} # 创建一个自定义网络，让服务间可以通过服务名(如'db')通信